name: Build pipeline
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.20'
      - name: Build
        run: |
          make build-launch-config
      - name: Upload artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: launch-config-binary
          path: target/launch-config
  publish-docker-image:
    if:  ${{ github.event_name == 'push' }}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: 'master'
          create_tag: true
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: launch-config-binary
          path: target/launch-config
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build timestamp
        id: docker-build-timestamp
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "ts_value=$TIMESTAMP" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          build-args: |
            BUILD_DATE=${{ steps.docker-build-timestamp.outputs.ts_value }}
            BUILD_VERSION=${{ steps.calculate-version.outputs.version-string }}
            VCS_REF=${{ github.sha }}
          tags: ghcr.io/bitshifted/launchcode:${{ steps.calculate-version.outputs.version-string }}
       
